fix: add check commands in pre commit file

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,5 +5,8 @@ cd "$(git rev-parse --show-toplevel)"
 # Run PHP syntax check
 composer php-lint || exit 1
 
-# Run Prettier formatting
-composer format || exit 1
+# Run Prettier formatting check
+if ! composer format-check; then
+  echo "Prettier check failed! Run 'composer format' to fix formatting."
+  exit 1
+fi
